#' Export animation as GIF.
#'
#' @param file_in The name of the html file which the data are to be read from.
#' @param fps Frames per second of the gif.
#' @param file_out The name of the file where the gif will be saved .
#' @param type \code{"typedR"} or \code{"custom"} (TODO) html files.
#' @param options Additional options for custom html files. A \code{list} of details which needs
#' to include \code{length} of animation, see below \code{Additionl Options} and \code{example}
#' section below for more details.
#' @description
#' Export html animation as GIF.
#' @details
#' This function renders html animations into gif. It can be used to with other html files
#' which is not generated by \code{typedR}, by default the details of the previously genreated
#' \code{typedR} animation will be store,
#' therefore additional parameters are not required.
#' However, to render other html files, additional parameters will need to be provided. See above parameters.
#' @note
#' A headless browser is used to capture the animation, therefore it will take approximately
#' the length of the animation to render it into GIF.
#' @section Additional Options:
#' Additional parameters required for custom html files. This needs to passed as a \code{list}.
#' \itemize{
#'  \item{\code{length}:  }{Length of the animation in milliseconds.}
#'  \item{\code{selector}:  }{CSS selector of the element in the DOM to capture.
#'  \code{body} will be used by default.}
#' }
#' @author
#' Charco Hui
#' @examples
#' \not
#' mywidget = typedR(text = "apply(matrix(1:4, nc=2), 2, mean)", theme = "mac",
#'        ratio = 0.8, speed = 500, background_col = "lightblue",
#'        width = 640, height = 480)
#' htmlwidgets::saveWidget(mywidget, "mywidget.html")
#' library(chromote)
#' library(magick)
#' html2gif("mywidget.html")
#' @importFrom progress progress_bar
#' @export
html2gif = function(file_in, fps = 10, file_out = "mygif.gif", type = "typedR",
                    options = NULL) {
  if(!exists("file")) {
    stop("Provide file name.")
  }
  if(fps > 15) {
    warning("fps > 15. Due to the nature of this function,
            it may take a while to complete")
  }
  if("tmp_capture" %in% list.files()) {
    unlink("tmp_capture", recursive = T)
  }
  if(type == "typedR") {
    if(is.null(getOption("typedR.prev"))) {
      stop("There is nothing to render")
    }
    nchar_txt = nchar(getOption("typedR.prev")$strings)
    speed_txt = getOption("typedR.prev")$typeSpeed
    anim_length = nchar_txt * speed_txt
    css_selector = "#term_panel"
  } else if(type == "custom") {
    anim_length = options$length
    if(is.null(options$selector)) {
      css_selector = "body"
    } else {
      css_selector = options$selector
    }

  } else {
    stop("Provide a valid type. typedR or custom.")
  }
  message("By default the options of the previous typedR object will be used
        make sure you are rendering your newest animation.\n")
  # tmp_dir = tempdir()
  odir = getwd()
  tmp_dir = paste0(odir, "/tmp_capture")
  dir.create(tmp_dir)
  num_img = anim_length * (fps / 10) / 1000
  time_per_img = anim_length / num_img / 1000
  file_i = sprintf("%02d", 1:num_img)
  # PNG
  b = ChromoteSession$new(width = getOption("typedR.prev")$width,
                          height = getOption("typedR.prev")$height)
  b$Page$navigate(paste0("file://", odir, "/", file_in))
  sink(file = paste0(tmp_dir, "/tmp_sink.txt"))
  pb = progress_bar$new(format = "  Rendering PNG [:bar] :percent eta: :eta",
                        total = num_img)
  for(i in 1:num_img) {
    invisible(b$screenshot(selector = css_selector, region = "padding",
                 filename = paste0(tmp_dir, "/img", file_i[i], ".png")))
    pb$tick()
    Sys.sleep(time_per_img)
  }
  sink()
  b$close()
  # GIF
  pb = progress_bar$new(format = "  Converting GIF [:bar] :percent eta: :eta",
                        total = num_img)
  setwd("./tmp_capture")
  imgs = list.files(pattern = "*.png") %>% sort() %>% as.list()
  for(i in seq_along(imgs)) {
    imgs[[i]] = image_read(imgs[[i]])
    pb$tick()
    Sys.sleep(1 / num_img)
  }
  setwd(odir)
  imgs %>% image_join() %>% image_animate(fps = fps) %>%
    image_write(file_out)
}
